version: "3"

services:
  webapp:
    build: .
    ports:
      - "5173:5173"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend:
